### ISSUE TITLE
Documentation Outdated

### ISSUE THREAD

**Issue by 4yx** [VPTOfficial/VistaPanel-Docs#2]
Our documentation was last updated in 2018. Since then, changes have happened.
Also, the docs do not include tutorials for the scripts.
I will personally check it out and try to update them when I have time, but in the meantime, if anyone is available, could you please check it out and see if you have any time to update them?

**Comment by aa22dev** [comment]
I don't think those changes will effect the docs because the docs contains 25 themes name and the repo includes 25 themes :wink: 

I'll add docs about scripts if i have time. Right now i am busy.

**Comment by aa22dev** [comment]
This documentation will now be referred to as old documentation.
New documentation can be found at https://github.com/WybeNetwork/Documentation
